INSERT INTO [dbo].[Product] ([ID], [SupplierID], [ProductName], [EmployeeInitials], [Price], [Origin], [Category], [Packaging], [WeightPerUnit], [Unit], [StockLevel], [EntryDate], [Description], [DetailDescription], [ImageUrl], [ProductUrl]) VALUES (N'b7400067-9ed4-4e0e-8fb4-1204877655b7', N'Dangote', N'Dangote', N'RPN', CAST(40.4700 AS Money), N'Nigeria', N'Cement', N'Bagged', 50, N'kg', 500, N'2021-04-07 00:10:01', N'Heavy Structure', N'Heavy Structural Bridges, Multi Storey Water retaining Structures', N'../assets/img/cement/Dangote', N'/product/dangote')
INSERT INTO [dbo].[Product] ([ID], [SupplierID], [ProductName], [EmployeeInitials], [Price], [Origin], [Category], [Packaging], [WeightPerUnit], [Unit], [StockLevel], [EntryDate], [Description], [DetailDescription], [ImageUrl], [ProductUrl]) VALUES (N'dfbbbda4-5778-458b-938c-1a79fbc0aecd', N'CIMAF', N'CIMAF Classic', N'FTA', CAST(51.1800 AS Money), N'Togo', N'Cement', N'Bagged', 50, N'kg', 350, N'2021-04-07 00:10:01', N'Blocks Manufacturing, Pre-cast products,', N'Block-laying and general masonry applications (joinery mortar, rendering/plastering etc) ', N'../assets/img/cement/cimaf-classic', N'/product/cimaf-classic')
INSERT INTO [dbo].[Product] ([ID], [SupplierID], [ProductName], [EmployeeInitials], [Price], [Origin], [Category], [Packaging], [WeightPerUnit], [Unit], [StockLevel], [EntryDate], [Description], [DetailDescription], [ImageUrl], [ProductUrl]) VALUES (N'0e4ffc2e-bdd7-4fa9-b907-c5db63226595', N'CIMAF', N'CIMAF Ultimate', N'DDN', CAST(35.2300 AS Money), N'Togo', N'Cement', N'Bagged', 50, N'kg', 900, N'2021-04-07 00:10:01', N'Heavy structural applications', N'(reinforced concrete) Ultra-high performance and high-performance concrete Heavy traffic pavements High, Strength Concrete products (kerbs, pre-stressed slabs, culverts, concrete pipes, concrete blocks)', N'../assets/img/cement/cimaf-ultimate', N'/product/cimaf-ultimate')
INSERT INTO [dbo].[Product] ([ID], [SupplierID], [ProductName], [EmployeeInitials], [Price], [Origin], [Category], [Packaging], [WeightPerUnit], [Unit], [StockLevel], [EntryDate], [Description], [DetailDescription], [ImageUrl], [ProductUrl]) VALUES (N'937a5e67-2acc-4d87-8b30-cdde31c5bc69', N'GHACEM', N'GHACEM Super Extra', N'FTA', CAST(34.1800 AS Money), N'Ghana', N'Cement', N'Bagged', 50, N'kg', 300, N'2021-04-06 23:51:15', N'Heavy Structure', N'Heavy Structural Bridges, Multi Storey Water retaining Structures', N'../assets/img/cement/ghacem-s-e', N'/product/ghacem-super-extra')
INSERT INTO [dbo].[Product] ([ID], [SupplierID], [ProductName], [EmployeeInitials], [Price], [Origin], [Category], [Packaging], [WeightPerUnit], [Unit], [StockLevel], [EntryDate], [Description], [DetailDescription], [ImageUrl], [ProductUrl]) VALUES (N'342994e4-7d08-470a-9e56-de17a28c420b', N'GHACEM', N'GHACEM Super Strong', N'FTA', CAST(46.1800 AS Money), N'Ghana', N'Cement', N'Bagged', 50, N'kg', 200, N'2021-04-06 23:51:15', N'Blocks Manufacturing, Pre-cast products,', N'Blocks Manufacturing, Pre-cast products, High strength Structural Applications  ', N'../assets/img/cement/ghacem-s-s', N'/product/ghacem-super-strong')
INSERT INTO [dbo].[Product] ([ID], [SupplierID], [ProductName], [EmployeeInitials], [Price], [Origin], [Category], [Packaging], [WeightPerUnit], [Unit], [StockLevel], [EntryDate], [Description], [DetailDescription], [ImageUrl], [ProductUrl]) VALUES (N'de8aa7d9-90c6-44ac-8d01-eb6f11e91919', N'GHACEM', N'GHACEM Super Rapid', N'FTA', CAST(36.2300 AS Money), N'Ghana', N'Cement', N'Bagged', 50, N'kg', 100, N'2021-04-06 23:51:15', N'fast drying time', N'That is; Super Rapid and Super Strong. It has a finer texture 
compared to the other grades, gives consumers extra blocks than the
other grades as well as stronger than the other grades.
Normal Structural application,Block Laying, Internal & External Plastering', N'../assets/img/cement/ghacem-s-r', N'/product/ghacem-super-rapid')
